# Generated by Django 4.2.1 on 2023-05-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapipermission',
            name='user_api_permission_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_api_permission', to='user_api.userapipermissionname'),
        ),
    ]
