# Generated by Django 4.2.1 on 2023-05-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='production_api',
            field=models.CharField(default='live_api_893bc5a3-60a8-4f20-868d-6b35402211fd', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='test_api',
            field=models.CharField(default='test_api_0c5674ae-5754-4216-a62f-e4b8be77d9cd', max_length=255),
        ),
    ]
