# Generated by Django 4.2.1 on 2023-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0002_alter_apiaccess_production_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='production_api',
            field=models.CharField(default='live_api_012e2190-daeb-4b05-b21a-23dda6ccdf7a', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='test_api',
            field=models.CharField(default='test_api_59ed0937-8543-43cd-b130-ea2c4b20d3fb', max_length=255),
        ),
    ]
