# Generated by Django 4.2.1 on 2023-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0003_alter_apiaccess_production_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='production_api',
            field=models.CharField(default='live_api_979aa5d7-b61a-482a-95aa-1e3f9b30d882', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='test_api',
            field=models.CharField(default='test_api_8d1ffad4-682d-48d4-bdbf-86cb3c462256', max_length=255),
        ),
    ]
