# Generated by Django 4.2.1 on 2023-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0004_alter_apiaccess_production_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='production_api',
            field=models.CharField(default='live_api_53ed369b-754b-46ce-a638-d23840a16606', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='test_api',
            field=models.CharField(default='test_api_a537d09a-526b-4e9d-9385-b7d8b37f44be', max_length=255),
        ),
    ]
