# Generated by Django 4.2.1 on 2023-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0005_alter_apiaccess_production_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='production_api',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='test_api',
            field=models.CharField(max_length=255),
        ),
    ]
