# Generated by Django 4.2.1 on 2023-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_customre', '0006_alter_apiaccess_production_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
